### ISSUE TITLE
Maybe put the df_ functions here?

### ISSUE THREAD

**Issue by dtkaplan** [ProjectMOSAIC/mosaicCore#1]
What do you think about putting the df_stats and related functions here?

**Comment by rpruim** [comment]
Maybe.  I've been considering it.

But I don't want `mosaicCore` to become full of useful exported functions really.  Then it will just become a remake of `mosaic`.

Plus, `df_stats()` has a clear focus and belongs in something more focussed than `mosaicCore`, I think.

I guess I'm really waiting to figure out what else belongs *with* `df_stats()`.  I think that will help me answer the question.  If it really stand-alone, I guess it belongs either in `ggformula` or in a package by itself.  

I'm not a fan of large diffuse packages like `mosaic`.  They are unwieldy to manage (and run up against CRAN proscriptions).  Better to have smaller, focused packages that each do a set of related tasks.

The purpose of `mosaicCore` is to support the other packages more than to support end users.  Of course, there are gray areas when a function is useful both internally and externally.  But I think of `df_stats()` as being primarily an external function.

**Comment by rpruim** [comment]
I can also see `df_stats()` staying in `ggformula` (at least for now).  Much like `mean_se()` is in `ggplot2`.  If `mosaic` is going to require `ggformula`, then it will come along for free for anyone using `mosaic`.

But I don't have a good sense yet for how `mosaicModel` is going to shake out (and what things from there are going to move to `ggformula`).  I think we can make a better decision when that package is closer to finished.

Of course, if `mosaicModel` will depend on `ggformula`, then having it in `ggformula` works for that too.

**Comment by rpruim** [comment]
I'm trying the move of `df_stats()` from `ggformula` to `mosaicCore`.

My hope is still that `mosaicCore` will never need to be placed on the search path.  Instead, other packages (like `ggformula`) can re-export `df_stats()`.

We can always move this back into `ggformula` or into some other package if that ends up being the better choice.
