### ISSUE TITLE
capture name in df_stats() when summarizing function returns a single named value.

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/mosaicCore#13]
```r
prop(~sex, data = KidsFeet)
##         B 
## 0.5128205 
df_stats(~sex, data = KidsFeet, prop)
##    prop_sex
## 1 0.5128205
```

Ideally, the name returned from `df_stats()` should be `prop_B`.  The trouble is that `aggregate()` doesn't keep the names in this situation.  (It does when there are 2 or more names.)

**Comment by rpruim** [comment]
As far as I can tell, the only way to fix this is to create a custom version of `aggregate()` that retains the names in this case.  I've done that.  All existing tests pass, and we now get 

```r
df_stats(~substance | sex, data = mosaicData::HELPmiss, prop)
##      sex prop_alcohol
## 1   male        0.412
## 2 female        0.333
df_stats(~substance | sex, data = mosaicData::HELPmiss, prop(success = "cocaine"))
##      sex prop_cocaine
## 1   male        0.320
## 2 female        0.369
prop(~substance | sex, data = mosaicData::HELPmiss)
##   prop_alcohol.male prop_alcohol.female 
##               0.412               0.333 
prop(~substance | sex, data = mosaicData::HELPmiss, sep = "|")
##   prop_alcohol|male prop_alcohol|female 
##               0.412               0.333 
```

**NOTE:**  I'm in favor of this change, but it will break old code that relies on the names returned.  This is a bigger issue for `prop()` than it is for `df_stats()` since `prop()` has been around longer.  I like the change because it demystifies which proportion `prop()` is calculating and make the output for `prop` and `props` match in `df_stats()`:

```r
df_stats(~substance | sex, data = mosaicData::HELPmiss, prop, props)
##      sex prop_alcohol prop_alcohol prop_cocaine prop_heroin prop_missing
## 1   male        0.412        0.412        0.320       0.267      0.00000
## 2 female        0.333        0.333        0.369       0.288      0.00901
```

**Comment by dtkaplan** [comment]
I like the change, too.

The cost in terms of newly broken software is real, but for the large
majority of people just use the names for guiding the human reader. Those
who make downstream use of the output of `df_stats()` will get a pretty
targeted error message (such as, "no such variable") and it will be
straightforward to find the problem. And when they do fix it, they will
say, "Why did I ever think it would be `prop_substance` instead of
`prop_alcohol`?

**Comment by rpruim** [comment]
I'll take that as an endorsement of this plan and continue moving in this direction.

Side note:  I've been teaching my students to use `props()` rather than `prop()` with `df_stats()` because (a) the naming is better and (b) you can choose which version of the proportion you want after the fact.  But fixing this will make me reconsider using `prop()`.

Note: one place that the naming will get people is when they use `do()` and then use the resulting data frame afterwards.
