### ISSUE TITLE
Add one-sided formulas to makeFun() in branch one-sided-makeFun

### ISSUE THREAD

**Issue by dtkaplan** [ProjectMOSAIC/mosaicCore#38]
I've added a new branch to update `mosaicCore` 0.9.0 that enables `makeFun()` to handle one-sided formulas **if** the `mosaicCalc` package happens to be installed. I'm looking for Randy's review and comments and, if appropriate, integration into the next CRAN release with `install_github()` working in the meanwhile. The relevant version of `mosaicCalc` is 

```r
remotes::install_github("ProjectMOSAIC/mosaicCalc", ref="devel-0.6")
```
which will soon be submitted to CRAN (with a few modifications yet to be made) as version 0.6 of `mosaicCalc`.

As originally designed, `makeFun.formula()` accepts only two-sided formulas: the left-hand side is an expression, the right-hand side lists the arguments in the order they are to appear. Thus, `f <- makeFun(x+y ~ y + x)` will construct a function with `y` as the first argument and `x` as the second.

In the `mosaicCalc` package, many functions use the right-hand side to indicate not a list of arguments but one or more with-respect-to arguments. For example, `D(f(y,x) ~ x)` returns a function with `x` as the first argument and `y` as the second. This creates some confusion with students (for whom the `mosaicCalc` package was designed) who don't look carefully at the argument list of the functions created with `D()`. 

Version 5.8 of `mosaicCalc` has re-worked the `D()` and `antiD()` functions to give them much more powerful symbolic capabilities (inherited from the `Deriv` and `Ryacas` packages). Along with this change, `D()` now structures the arguments in a **canonical order**, regardless of which with the with-respect-to argument.

Branch "one-sided-makeFun" reworks `makeFun.formula()` so that it can accept a one-sided formula *only if `mosaicCalc` is installed`. Given such a formula, in the presence of `mosaicCalc` (whether loaded or not) the argument list of the result will be ordered **canonically**.  In the absence of `mosaicCalc` the behavior reverts to accepting only two-sided formulas and returns exactly the same function as in the previous version of `mosaicCore`. (The error message is slightly changed.)

This "one-sided-makeFun" branch builds and checks cleanly either with or without `mosaicCalc` being installed. If `mosaicCalc` is not installed, a "note" is generated by the check to the effect of "the suggested package `mosaicCalc` is not installed." 

This branch bumps the version number to 0.9.1 (from 0.9.0) and adds unit tests for both the old `makeFun.formula()` behavior and the new behavior in the presence of `mosaicCalc`. I have not modified the documentation for `makeFun()`; it seems unnecessarily complicated to introduce the one-sided behavior with a condition that `mosaicCalc()` is needed for it to work.

**Comment by rpruim** [comment]
I've taken a brief look at this, and my main concern is the funky dependence on {mosaicCalc} presence for {mosaicCore} behavior. I don't immediately see a downside to just having the new behavior baked into {mosaicCore} -- whether or not {mosaicCalc} is installed.  It looks like we would only need to move two additional small functions over to {mosaicCore} (`infer_RHS()` and `sort_args_by_convention()`) to get all of the behavior contained within {mosaicCore}.  I would suggest moving those two functions and dropping the check for {mosaicCalc} unless I'm missing something.

Documentation and examples should be updated to match.

**Comment by dtkaplan** [comment]
Thanks.

I agree about the funky dependence. I'll duplicate the functionality of
`infer_RHS` and `sort_args_by_convention` into non-exported `{mosaicCore}`
functions and modify `makeFun.formula()` accordingly and add some tests to
`{mosaicCore}`.

- Danny

**Comment by rpruim** [comment]
Alternatively, just move the functions and export them if you need them elsewhere in {mosaicCalc}.

**Comment by dtkaplan** [comment]
I've set up `{mosaicCore}` to remove the dependency on `{mosaicCalc}`.  

New: 

1. The "one-sided" functionality has been extended to two-sided formulas like `a*x^2 + b ~ .`
2. Removed the `{mosaicCore}` error message rejecting one-sided formulas in `makeFun()`. Rationale: there's no reason to have different behavior depending on whether `{mosaicCalc}` is installed.
3. Documentation for `makeFun()` tweaked to indicate the one-sided functionality.

Version number remains at 0.9.1 (per my first push about this issue). Checks pass with no errors/warnings/notes.

I think this is ready to go for CRAN, but I leave submitting it to @rpruim

**Comment by dtkaplan** [comment]
My one-sided version of makeFun() neglected to exclude "pi" as an argument to a function. I've fixed that here, with a very slight change to `infer_RHS()` and a corresponding test in the tests/ directory. Passes all tests cleanly.  I made the changes in branch one-sided-makeFun, so you'll have to merge them into main. Sorry for the extra work.

**Comment by rpruim** [comment]
Good catch.

**Comment by rpruim** [comment]
I've merged this into master and pushed.  Basic checks all passed on my end as well.  Should be getting close to submitting to CRAN.
