### ISSUE TITLE
Warnings from makeFun

### ISSUE THREAD

**Issue by dtkaplan** [ProjectMOSAIC/mosaicCore#7]
The mosaicCore:::makeFun.formula function generates warnings about "implicit variables without default values" at times where I think it's not appropriate, e.g.
```{r}
foo <- D(a * x^2 + b * x ~ x, a = 1, b = 1)
D(foo(x) ~ x)
```

```
function (x, a = 1, b = 1) 
a * 2
Warning message:
In makeFun.formula(formula, ...) :
  Implicit variables without default values (dangerous!):  a, b
```

I'm writing a vignette for `mosaicCalc` and I'd like to fix this behavior.

The main question: Am I right that the behavior is inappropriate? 

A secondary question: Do we need the warning at all?

For instance, even with 
```{r}
g <- makeFun(a * x ~ x)
```

The evaluation `g(2)` generates a correct error:
```
Error in g(2) : argument "a" is missing, with no default
```
Isn't this enough?

**Comment by rpruim** [comment]
Glad to hear things are happening for `mosaicCalc`.  I'm sure we put this in for a reason, even if there is a bug now.  But I haven't thought about this recently enough to know (a) whether we still want it or (b) what is causing the warning when you don't expect it.

**Comment by rpruim** [comment]
There is an easy "fix": just change the default value of `suppress.warnings` to TRUE.

Is that what we want?
