### ISSUE TITLE
Column names in df_stats() output scrambled for multiple two-number stats.

### ISSUE THREAD

**Issue by dtkaplan** [ProjectMOSAIC/mosaicCore#8]
```{r}
library(mosaic)
df_stats(~ hp, data = mtcars, 
              spread = quantile(c(0.1, 0.9)), 
              percentiles = range )
```

```
##   spread_10% percentiles_90% spread_1 percentiles_2
## 1         66           243.5       52           335
```

The output should be:
```
##  spread_1 spread_2 percentiles_10%  percentiles_90%
## 1         52         335                       66                    243.5
```

**Comment by dtkaplan** [comment]
@rpruim I've found the mistake. A fix involving just a few lines of `df_stats()` is in branch issue008. It passes the checks with no warnings, errors, or notes.

I'll leave it to you to merge branch issue008 with master. At some point perhaps you can explain to me how to do a proper pull request: is it that I fork the repository first?

-Danny

**Comment by rpruim** [comment]
Did you create a test?

**Comment by dtkaplan** [comment]
I've added the test corresponding to issue 8 and pushed it (and the proposed changes to the code) in the issue008 branch.

I realized I shouldn't have closed this issue until the changes in the issue008 branch are merged into master. So I re-opened it. 

Again, I'll leave it to you to do the merge, so that you have an opportunity to ask sensible questions like the one from yesterday: "Did you create a test?"

**Comment by dtkaplan** [comment]
@rpruim @nicholasjhorton I'm going to merge the changes for this issue into the master branch.

**Comment by rpruim** [comment]
OK.  I was intending to, but hadn't gotten to it yet.

**Comment by rpruim** [comment]
We need to be more careful and try this again.  The changes in the `issue008` branch were breaking for `ggformula`, and I'm not sure they were exactly what we want.  Once we get this all sorted, we can figure out if we need to also make changes to `ggformula` because of desirable name changes.  But note: changing the names will be a **breaking change** for existing code that is built based on the current names.

**Comment by rpruim** [comment]
I fixed the original issue and avoided breaking changes in some other situations.

```r
 df_stats(~ cyl, data = mtcars)
##   min Q1 median Q3 max   mean       sd  n missing
## 1   4  4      6  8   8 6.1875 1.785922 32       0

df_stats(~ hp, data = mtcars, mn = ci.mean, md = ci.median, Q  = quantile)
##   mn_lower mn_upper md_lower md_upper Q_0% Q_25% Q_50% Q_75% Q_100%
## 1 121.9679 171.4071      109      175   52  96.5   123   180    335
```

Now we just need to confirm that we like the naming conventions in use.   Here are some examples.  I think these all seem reasonable and are what I currently intend them to be.

```r
df_stats(~ hp, data = mtcars, ci.mean, md = ci.median, Q  = quantile, max, range)
##      lower    upper md_lower md_upper Q_0% Q_25% Q_50% Q_75% Q_100% max_hp range_hp_1 range_hp_2
## 1 121.9679 171.4071      109      175   52  96.5   123   180    335    335         52        335
```

Note: "long names" (that include the variable being summarised) are only used in the case that the argument is not named and does not name its output (see `max` and `range` above).  Else we prefer to use the names provided by the user or by the function the user specifies.

**Comment by rpruim** [comment]
Here's one I don't like

```r
df_stats(~substance, data = HELPrct, prop)
##   prop_substance
## 1      0.3907285
```
I'd prefer the name be `prop_alcohol`.  The trouble is that in this case `aggregate()` doesn't keep the name produced by `prop()` (which currently names the output `alcohol`).

Not sure if there is an easy fix for this.

**Comment by rpruim** [comment]
Just confirming that after all the rep reworking this is still working as desired:

```r
df_stats(~ cyl, data = mtcars)
##   min Q1 median Q3 max   mean       sd  n missing
## 1   4  4      6  8   8 6.1875 1.785922 32       0
df_stats(~ hp, data = mtcars, mn = ci.mean, md = ci.median, Q  = quantile)
##   mn_lower mn_upper md_lower md_upper Q_0% Q_25% Q_50% Q_75% Q_100%
## 1 121.9679 171.4071      109      175   52  96.5   123   180    335
```
